export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';

export const SAVE_SESSION_REQUEST = 'SAVE_SESSION_REQUEST';
export const SAVE_SESSION = 'SAVE_SESSION';
