export const FETCH_USER_ACTION_TYPES = {
    FETCH_USER_REJECTED: 'FETCH_USER_REJECTED',
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    // FETCH_USER_FULFILLED is similar to UPDATE_USER_FULFILLED
    // hence I use UPDATE_USER_FULFILLED for DRY code
};

export const UPDATE_USER_ACTION_TYPES = {
    UPDATE_USER_FULFILLED: 'UPDATE_USER_FULFILLED',
    UPDATE_USER_REJECTED: 'UPDATE_USER_REJECTED',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
};

export const SAVE_SESSION_ACTION_TYPES = {
    SAVE_SESSION: 'SAVE_SESSION',
    SAVE_SESSION_REQUEST: 'SAVE_SESSION_REQUEST',
};

export const REMOVE_SESSION = 'REMOVE_SESSION';
