export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';

export const SAVE_SESSION_REQUEST = 'SAVE_SESSION_REQUEST';
export const SAVE_SESSION = 'SAVE_SESSION';
export const REMOVE_SESSION = 'REMOVE_SESSION';
