export const SELECT_COURSE_ACTION_TYPES = {
    SELECT_COURSE: 'SELECT_COURSE',
    SELECT_COURSE_REQUEST: 'SELECT_COURSE_REQUEST',
};

export const SELECT_MODE_ACTION_TYPES = {
    SELECT_MODE: 'SELECT_MODE',
    SELECT_MODE_REQUEST: 'SELECT_MODE_REQUEST',
};

export const SELECT_OPPONENT_ACTION_TYPES = {
    SELECT_OPPONENT: 'SELECT_OPPONENT',
    SELECT_OPPONENT_REQUEST: 'SELECT_OPPONENT_REQUEST',
};

export const SET_ONLINE_USERS_ACTION_TYPES = {
    SET_ONLINE_USERS: 'SET_ONLINE_USERS',
    SET_ONLINE_USERS_REQUEST: 'SET_ONLINE_USERS_REQUEST',
};

export const SET_CHALLENGE_REQ_STATUS_ACTION_TYPES = {
    SET_CHALLENGE_REQ_STATUS: 'SET_CHALLENGE_REQ_STATUS',
    SET_CHALLENGE_REQ_STATUS_REQUEST: 'SET_CHALLENGE_REQ_STATUS_REQUEST',
};
