export const FETCH_COURSES_ACTION_TYPES = {
    FETCH_COURSES_FULFILLED: 'FETCH_COURSES_FULFILLED',
    FETCH_COURSES_REJECTED: 'FETCH_COURSES_REJECTED',
    FETCH_COURSES_REQUEST: 'FETCH_COURSES_REQUEST',
};

export const SELECT_COURSE_ACTION_TYPES = {
    SELECT_COURSE: 'SELECT_COURSE',
    SELECT_COURSE_REQUEST: 'SELECT_COURSE_REQUEST',
};

export const SELECT_MODE_ACTION_TYPES = {
    SELECT_MODE: 'SELECT_MODE',
    SELECT_MODE_REQUEST: 'SELECT_MODE_REQUEST',
};

export const SELECT_OPPONENT_ACTION_TYPES = {
    SELECT_OPPONENT: 'SELECT_OPPONENT',
    SELECT_OPPONENT_REQUEST: 'SELECT_OPPONENT_REQUEST',
};

export const SET_ONLINE_USERS_ACTION_TYPES = {
    SET_ONLINE_USERS: 'SET_ONLINE_USERS',
    SET_ONLINE_USERS_REQUEST: 'SET_ONLINE_USERS_REQUEST',
};

export const SET_CHALLENGE_REQ_STATUS_ACTION_TYPES = {
    SET_CHALLENGE_REQ_STATUS: 'SET_CHALLENGE_REQ_STATUS',
    SET_CHALLENGE_REQ_STATUS_REQUEST: 'SET_CHALLENGE_REQ_STATUS_REQUEST',
};

export const SET_CHALLENGE_END_STATUS_ACTION_TYPES = {
    SET_CHALLENGE_END_STATUS: 'SET_CHALLENGE_END_STATUS',
    SET_CHALLENGE_END_STATUS_REQUEST: 'SET_CHALLENGE_END_STATUS_REQUEST',
};

export const SET_CHALLENGE_ROOM_ACTION_TYPES = {
    SET_CHALLENGE_ROOM: 'SET_CHALLENGE_ROOM',
    SET_CHALLENGE_ROOM_REQUEST: 'SET_CHALLENGE_ROOM_REQUEST',
};

// update challenge store of opponent to be in sync with that of 
// challenger
export const UPDATE_CHALLENGE_STORE_ACTION_TYPES = {
    UPDATE_CHALLENGE_STORE: 'UPDATE_CHALLENGE_STORE',
    UPDATE_CHALLENGE_STORE_REQUEST: 'UPDATE_CHALLENGE_STORE_REQUEST',
};

// actions for setting the question to be displayed in quiz component
export const SET_CURRENT_QUESTION_ACTION_TYPES = {
    SET_CURRENT_QUESTION: 'SET_CURRENT_QUESTION',
    SET_CURRENT_QUESTION_REQUEST: 'SET_CURRENT_QUESTION_REQUEST',
};

// actions for setting all questions in quiz component
export const SET_QUESTIONS_ACTION_TYPES = {
    SET_QUESTIONS: 'SET_QUESTIONS',
    SET_QUESTIONS_REQUEST: 'SET_QUESTIONS_REQUEST',
};
