export const SELECT_COURSE_ACTION_TYPES = {
    SELECT_COURSE: 'SELECT_COURSE',
    SELECT_COURSE_REQUEST: 'SELECT_COURSE_REQUEST',
};

export const SELECT_MODE_ACTION_TYPES = {
    SELECT_MODE: 'SELECT_MODE',
    SELECT_MODE_REQUEST: 'SELECT_MODE_REQUEST',
};

export const SELECT_OPPONENT_ACTION_TYPES = {
    SELECT_OPPONENT: 'SELECT_OPPONENT',
    SELECT_OPPONENT_REQUEST: 'SELECT_OPPONENT_REQUEST',
};
